# Generated by Django 4.1 on 2022-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_parcel_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='surname',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('On the Route', 'On the Route'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], max_length=200, null=True),
        ),
    ]
